version: '3.9'

services: 
    
    superheroes-api:
        build: 
            context: ./superheroes-api/.
            dockerfile: Dockerfile
        image: superheroes-api
        container_name: practica5_superheroes-api_1
        volumes:
            - ./superheroes-api/.:/api
            - /api/node_modules
        ports: 
            - "8000:8000"
        depends_on: 
            - db
        links:
            - db:db
        env_file: ./superheroes-api/connection/process.env
        environment: 
            - MONGO_HOSTNAME=localhost
            - MONGO_PORT=27017
            - MONGO_DB=superheroes
    
    db:
        image: mongo
        container_name: mongodb
        ports:
            - "27017:27017"